//==================================================
// File name: SearchBar.jsx
//==================================================
// Description:
// Provides a controlled React form for entering and
// submitting a weather-search location.
//
// STEP 4 demonstrates:
// - React form events
// - controlled input state
// - onChange handling
// - onSubmit handling
// - preventDefault()
// - input normalization
// - basic validation
// - conditional error rendering
// - callback communication with the parent component
//
// Processing Workflow:
// 1. User enters a location.
// 2. onChange updates local cityInput state.
// 3. User submits the form.
// 4. Browser default submission is prevented.
// 5. Input is trimmed and validated.
// 6. Invalid input produces an error message.
// 7. Valid input is sent to App through onSearch.
// 8. Input and validation state are reset.
//
// Date: 31-Aug-2026
// Author: mghazel
// Version: 4.0
//==================================================

import { useState } from "react";

/**
 * Renders a controlled location-search form.
 *
 * @param {Object} props - Component properties.
 * @param {string} props.city
 * Currently selected application city.
 * @param {Function} props.onSearch
 * Callback invoked after a valid location is submitted.
 *
 * @returns {JSX.Element} Location-search form.
 */
function SearchBar({ city, onSearch }) {
  // --------------------------------------------------
  // Local Form State
  // --------------------------------------------------

  /**
   * Stores the current text entered into the search field.
   *
   * This value represents draft form input and is intentionally
   * separate from the selected application city in App.jsx.
   */
  const [cityInput, setCityInput] = useState("");

  /**
   * Stores a validation message for invalid submissions.
   */
  const [errorMessage, setErrorMessage] = useState("");

  /**
   * Handles changes to the controlled text input.
   *
   * Each keystroke updates cityInput state, which causes React
   * to re-render the component with the new input value.
   *
   * @param {React.ChangeEvent<HTMLInputElement>} event
   * Input change event generated by React.
   *
   * @returns {void}
   */
  function handleInputChange(event) {
    setCityInput(event.target.value);

    // Clear a previous validation error once the user starts
    // correcting the input.
    if (errorMessage) {
      setErrorMessage("");
    }
  }

  /**
   * Handles location-search form submission.
   *
   * Prevents the browser's default page reload, normalizes
   * whitespace, validates the location, and passes a valid
   * value to the parent App component.
   *
   * @param {React.FormEvent<HTMLFormElement>} event
   * Form submission event.
   *
   * @returns {void}
   */
  function handleSubmit(event) {
    event.preventDefault();

    const normalizedCity = cityInput.trim();

    if (!normalizedCity) {
      setErrorMessage(
        "Please enter a city or location."
      );
      return;
    }

    onSearch(normalizedCity);

    setCityInput("");
    setErrorMessage("");
  }

  return (
    <section className="search-section">
      <h2>Search Location</h2>

      <p className="current-location">
        Current location: <strong>{city}</strong>
      </p>

      <form
        className="search-form"
        onSubmit={handleSubmit}
        noValidate
      >
        <div className="form-group">
          <label htmlFor="city-search">
            City or Location
          </label>

          <input
            id="city-search"
            name="city"
            type="text"
            value={cityInput}
            onChange={handleInputChange}
            placeholder="Example: Vancouver"
            autoComplete="off"
            aria-describedby={
              errorMessage
                ? "city-search-error"
                : undefined
            }
          />

          {errorMessage && (
            <p
              id="city-search-error"
              className="form-error"
              role="alert"
            >
              {errorMessage}
            </p>
          )}
        </div>

        <button type="submit">
          Search
        </button>
      </form>

      <p className="step-note">
        STEP 4 processes the location through React
        form state and event handling. Live weather retrieval
        will be connected in a later step.
      </p>
    </section>
  );
}

export default SearchBar;